name: Workflow de ejemplo

on:
  push:
    branches:
      - main

jobs:
  imprimir_mensaje:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4
        
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Instalar dependencias
        run: npm install

      - name: Imprimir mensaje
        run: echo "¡Hola, mundo!"
      
      - name: Ejecutar pruebas
        run: npm test